title: Static Pages Demo

# Add compatibility for Github Pages so assets can be accessed.
baseurl: "/static-pages-demo"
url: ""

# Override the default with true so each author gets their own page rather than just being
# listed as items on the Staff page.
collections:
  authors:
    output: true

# Set layouts for posts and collections and the default layout for everything else. This
# means the layout can be removed from frontmatter of the post and collection pages.
# You also set your own values in defaults such as author or category.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
